# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1e0a9343f102235a57dc4727d912e46b9e28791d84519ac5d87ef5e9d5bf6247e986c1793200a6e5cc0089f224bc7138df0afcceee168ff36a025153f0eb581

test:
  secret_key_base: a046306da4cee79d1732db4134f9547ee9d97d9c50416184477ffc3701d711d82a30903eae4bddc65339375e5bec79ce8aef048c014ecc9bec9e5abe74667eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
